using System;
using System.Collections.Generic;

namespace CalRemix.UI.ElementalSystem
{
    public static class CalamityElements
    {
        internal static Dictionary<string, Element[]> Item = new()
        {
            #region Melee
            #region Pre-Hardmode
            { "AirSpinner", new Element[]{ Element.Impact, Element.Holy }},
            { "AmidiasTrident", new Element[]{ Element.Stab , Element.Water }},
            { "Aorta", new Element[]{ Element.Impact, Element.Dark }},
            { "BallOFugu", new Element[]{ Element.Stab, Element.Magic }},
            { "Basher", new Element[]{ Element.Impact, Element.Poison }},
            { "BladecrestOathsword", new Element[]{  Element.Slash, Element.Unholy }},
            { "BrokenBiomeBlade", new Element[]{ Element.Slash }},
            { "BurntSienna", new Element[]{ Element.Slash, Element.Holy }},
            { "DepthCrusher", new Element[]{ Element.Impact, Element.Water }},
            { "FellerofEvergreens", new Element[]{ Element.Slash }},
            { "FracturedArk", new Element[]{ Element.Slash, Element.Magic }},
            { "GaussDagger", new Element[]{ Element.Slash, Element.Machine }},
            { "GeliticBlade", new Element[]{ Element.Slash, Element.Poison }},
            { "GoldplumeSpear", new Element[]{ Element.Stab, Element.Holy }},
            { "MonstrousKnives", new Element[]{ Element.Stab }},
            { "MycelialClaws", new Element[]{ Element.Slash, Element.Poison }},
            { "OldLordClaymore", new Element[]{  Element.Slash, Element.Fire }},
            { "PerfectDark", new Element[]{ Element.Slash, Element.Dark }},
            { "RedtideSpear", new Element[]{ Element.Stab, Element.Water }},
            { "Riptide", new Element[]{ Element.Impact, Element.Water }},
            { "SaharaSlicers", new Element[]{ Element.Slash }},
            { "SausageMaker", new Element[]{ Element.Stab, Element.Dark }},
            { "SeashineSword", new Element[]{ Element.Slash, Element.Water }},
            { "SmokingComet", new Element[]{ Element.Impact, Element.Magic }},
            { "TaintedBlade", new Element[]{ Element.Slash, Element.Poison }},
            { "TeardropCleaver", new Element[]{ Element.Slash }},
            { "TheGodsGambit", new Element[]{ Element.Impact, Element.Poison }},
            { "UrchinFlail", new Element[]{ Element.Stab, Element.Poison }},
            { "UrchinMace", new Element[]{ Element.Stab, Element.Water }},
            { "VeinBurster", new Element[]{ Element.Slash, Element.Dark }},
            { "WindBlade", new Element[]{ Element.Slash, Element.Holy }},
            { "WulfrumScrewdriver", new Element[]{ Element.Stab, Element.Machine }},
            { "YateveoBloom", new Element[]{ Element.Stab, Element.Poison }},
            #endregion
            #region Hardmode
            { "AbsoluteZero", new Element[]{ Element.Slash, Element.Cold }},
            { "AbyssBlade", new Element[]{ Element.Slash, Element.Water }},
            { "AegisBlade", new Element[]{ Element.Slash, Element.Holy }},
            { "Aftershock", new Element[]{ Element.Slash }},
            { "AnarchyBlade", new Element[]{ Element.Slash, Element.Fire }},
            { "TrueArkoftheAncients", new Element[]{ Element.Slash, Element.Magic }},
            { "AstralBlade", new Element[]{ Element.Slash, Element.Magic }},
            { "AstralPike", new Element[]{ Element.Stab, Element.Magic }},
            { "AstralScythe", new Element[]{ Element.Slash, Element.Magic }},
            { "Avalanche", new Element[]{ Element.Slash, Element.Cold }},
            { "AxeofPurity", new Element[]{ Element.Slash, Element.Magic }},
            { "BalefulHarvester", new Element[]{ Element.Slash, Element.Dark }},
            { "TrueBiomeBlade", new Element[]{ Element.Slash }},
            { "BlightedCleaver", new Element[]{ Element.Slash, Element.Poison, Element.Fire }},
            { "Bonebreaker", new Element[]{ Element.Stab, Element.Poison }},
            { "Brimlance", new Element[]{ Element.Stab, Element.Unholy }},
            { "Brimlash", new Element[]{ Element.Slash, Element.Unholy, Element.Fire }},
            { "BrimstoneSword", new Element[]{ Element.Slash, Element.Unholy }},
            { "BrinyBaron", new Element[]{ Element.Slash, Element.Water }},
            { "Carnage", new Element[]{ Element.Slash, Element.Dark }},
            { "CatastropheClaymore", new Element[]{ Element.Slash, Element.Fire, Element.Cold }},
            { "TrueCausticEdge", new Element[]{ Element.Slash, Element.Poison }},
            { "CelestialClaymore", new Element[]{ Element.Slash, Element.Fire, Element.Cold }},
            { "ClamCrusher", new Element[]{ Element.Impact, Element.Water }},
            { "CometQuasher", new Element[]{ Element.Slash, Element.Magic }},
            { "DarklightGreatsword", new Element[]{ Element.Slash, Element.Cold, Element.Dark }},
            { "DiseasedPike", new Element[]{ Element.Stab, Element.Poison, Element.Machine }},
            { "EarthenPike", new Element[]{ Element.Stab }},
            { "EntropicClaymore", new Element[]{ Element.Slash, Element.Dark }},
            { "EutrophicScimitar", new Element[]{ Element.Slash, Element.Water }},
            { "EvilSmasher", new Element[]{ Element.Impact, Element.Dark }},
            { "ExaltedOathblade", new Element[]{ Element.Slash, Element.Dark }},
            { "FallenPaladinsHammer", new Element[]{ Element.Impact, Element.Unholy, Element.Fire }},
            { "FaultLine", new Element[]{ Element.Impact, Element.Fire }},
            { "FeralthornClaymore", new Element[]{ Element.Slash, Element.Poison }},
            { "FlarefrostBlade", new Element[]{ Element.Slash, Element.Fire, Element.Cold }},
            { "Floodtide", new Element[]{ Element.Slash, Element.Water }},
            { "ForbiddenOathblade", new Element[]{ Element.Slash, Element.Dark }},
            { "ForsakenSaber", new Element[]{ Element.Slash, Element.Fire }},
            { "GalvanizingGlaive", new Element[]{ Element.Stab, Element.Machine }},
            { "GrandGuardian", new Element[]{ Element.Slash, Element.Holy }},
            { "Greentide", new Element[]{ Element.Slash, Element.Poison }},
            { "HellfireFlamberge", new Element[]{ Element.Slash, Element.Fire }},
            { "HellionFlowerSpear", new Element[]{ Element.Stab, Element.Poison }},
            { "Hellkite", new Element[]{ Element.Slash, Element.Fire }},
            { "InfernaCutter", new Element[]{ Element.Slash, Element.Fire }},
            { "Lucrecia", new Element[]{ Element.Stab }},
            { "MajesticGuard", new Element[]{ Element.Slash }},
            { "MantisClaws", new Element[]{ Element.Slash }},
            { "Nebulash", new Element[]{ Element.Slash, Element.Machine, Element.Magic }},
            { "Oblivion", new Element[]{ Element.Impact, Element.Unholy }},
            { "Omniblade", new Element[]{ Element.Slash }},
            { "Pandemic", new Element[]{ Element.Impact, Element.Poison, Element.Machine }},
            { "Pwnagehammer", new Element[]{ Element.Impact, Element.Holy }},
            { "Quagmire", new Element[]{ Element.Impact, Element.Poison }},
            { "Roxcalibur", new Element[]{ Element.Impact }},
            { "Shimmerspark", new Element[]{ Element.Impact, Element.Cold }},
            { "SoulHarvester", new Element[]{ Element.Slash, Element.Dark }},
            { "StarnightLance", new Element[]{ Element.Stab, Element.Cold }},
            { "StormRuler", new Element[]{ Element.Slash, Element.Holy }},
            { "StormSaber", new Element[]{ Element.Slash, Element.Holy }},
            { "StygianShield", new Element[]{ Element.Impact }},
            { "SubmarineShocker", new Element[]{ Element.Slash, Element.Water, Element.Poison }},
            { "SulphurousGrabber", new Element[]{ Element.Impact, Element.Poison }},
            { "TenebreusTides", new Element[]{ Element.Stab, Element.Water }},
            { "BotanicPiercer", new Element[]{ Element.Stab }},
            { "TheMicrowave", new Element[]{ Element.Impact, Element.Magic }},
            { "TitanArm", new Element[]{ Element.Impact, Element.Magic }},
            { "OmegaBiomeBlade", new Element[]{ Element.Slash }},
            { "Tumbleweed", new Element[]{ Element.Impact, Element.Fire }},
            { "TyphonsGreed", new Element[]{ Element.Stab, Element.Water }},
            { "UltimusCleaver", new Element[]{ Element.Slash, Element.Dark }},
            { "Virulence", new Element[]{ Element.Impact, Element.Poison, Element.Machine }},
            { "VulcaniteLance", new Element[]{ Element.Stab, Element.Fire }},
            { "YinYo", new Element[]{ Element.Impact }},
            #endregion
            #region Godseeker
            { "ArkoftheCosmos", new Element[]{ Element.Slash, Element.Magic }},
            { "ArkoftheElements", new Element[]{ Element.Slash, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "Ataraxia", new Element[]{ Element.Slash, Element.Dark }},
            { "Azathoth", new Element[]{ Element.Impact }},
            { "BansheeHook", new Element[]{ Element.Stab }},
            { "CosmicDischarge", new Element[]{ Element.Impact, Element.Cold, Element.Dark }},
            { "CosmicShiv", new Element[]{ Element.Stab, Element.Magic, Element.Dark }},
            { "CrescentMoon", new Element[]{ Element.Impact, Element.Cold, Element.Dark }},
            { "DefiledGreatsword", new Element[]{ Element.Slash, Element.Holy, Element.Fire }},
            { "Devastation", new Element[]{ Element.Slash, Element.Cold, Element.Fire }},
            { "DevilsDevastation", new Element[]{ Element.Slash, Element.Unholy, Element.Fire }},
            { "DevilsSunrise", new Element[]{ Element.Slash, Element.Unholy, Element.Dark }},
            { "DraconicDestruction", new Element[]{ Element.Slash, Element.Fire }},
            { "DragonPow", new Element[]{ Element.Impact, Element.Holy, Element.Fire }},
            { "DragonRage", new Element[]{ Element.Slash, Element.Fire }},
            { "Earth", new Element[]{ Element.Slash, Element.Poison, Element.Cold, Element.Fire }},
            { "ElementalLance", new Element[]{ Element.Slash, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "ElementalShiv", new Element[]{ Element.Slash, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "EmpyreanKnives", new Element[]{ Element.Stab }},
            { "EssenceFlayer", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "Excelsus", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "Exoblade", new Element[]{ Element.Slash, Element.Machine, Element.Fire, Element.Cold}},
            { "GaelsGreatsword", new Element[]{ Element.Slash, Element.Unholy}},
            { "GalactusBlade", new Element[]{ Element.Slash, Element.Magic}},
            { "FourSeasonsGalaxia", new Element[]{ Element.Slash, Element.Magic}},
            { "GalaxySmasher", new Element[]{ Element.Impact, Element.Magic, Element.Dark }},
            { "GalileoGladius", new Element[]{ Element.Stab, Element.Cold, Element.Dark }},
            { "GildedProboscis", new Element[]{ Element.Stab, Element.Fire }},
            { "Grax", new Element[]{ Element.Slash }},
            { "GreatswordofJudgement", new Element[]{ Element.Slash }},
            { "HolyCollider", new Element[]{ Element.Slash, Element.Holy, Element.Fire }},
            { "IllustriousKnives", new Element[]{ Element.Stab, Element.Holy }},
            { "IridescentExcalibur", new Element[]{ Element.Slash }},
            { "Lacerator", new Element[]{ Element.Impact, Element.Poison, Element.Dark }},
            { "LifehuntScythe", new Element[]{ Element.Slash, Element.Poison }},
            { "LionHeart", new Element[]{ Element.Slash, Element.Machine }},
            { "MirrorBlade", new Element[]{ Element.Slash }},
            { "Mourningstar", new Element[]{ Element.Slash, Element.Fire }},
            { "Murasama", new Element[]{ Element.Slash, Element.Machine }},
            { "Nadir", new Element[]{ Element.Stab, Element.Dark }},
            { "NeptunesBounty", new Element[]{ Element.Slash, Element.Water }},
            { "Orderbringer", new Element[]{ Element.Slash }},
            { "Phaseslayer", new Element[]{ Element.Slash, Element.Machine }},
            { "PhosphorescentGauntlet", new Element[]{ Element.Impact, Element.Poison }},
            { "PhotonRipper", new Element[]{ Element.Slash, Element.Machine }},
            { "PlagueKeeper", new Element[]{ Element.Impact, Element.Poison, Element.Machine }},
            { "PrismaticBreaker", new Element[]{ Element.Slash, Element.Magic }},
            { "PulseDragon", new Element[]{ Element.Impact, Element.Machine }},
            { "RedSun", new Element[]{ Element.Slash, Element.Fire }},
            { "RemsRevenge", new Element[]{ Element.Impact, Element.Unholy, Element.Dark }},
            { "ScourgeoftheCosmos", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "SeekingScorcher", new Element[]{ Element.Slash, Element.Holy, Element.Fire }},
            { "BurningRevelation", new Element[]{ Element.Slash, Element.Holy, Element.Fire }},
            { "SolsticeClaymore", new Element[]{ Element.Slash }},
            { "VoidEdge", new Element[]{ Element.Slash, Element.Dark }},
            { "SpineOfThanatos", new Element[]{ Element.Slash, Element.Machine }},
            { "StellarContempt", new Element[]{ Element.Impact }},
            { "StellarStriker", new Element[]{ Element.Slash }},
            { "StreamGouge", new Element[]{ Element.Stab, Element.Magic, Element.Dark }},
            { "Swordsplosion", new Element[]{ Element.Slash }},
            { "Terratomere", new Element[]{ Element.Slash }},
            { "TerrorBlade", new Element[]{ Element.Slash, Element.Dark }},
            { "TheBurningSky", new Element[]{ Element.Fire }},
            { "TheEnforcer", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "TheLastMourning", new Element[]{ Element.Slash, Element.Dark, Element.Fire }},
            { "TheMutilator", new Element[]{ Element.Slash, Element.Poison, Element.Dark }},
            { "TheObliterator", new Element[]{ Element.Impact, Element.Magic, Element.Dark }},
            { "TheOracle", new Element[]{ Element.Impact, Element.Magic, Element.Holy }},
            { "TriactisTruePaladinianMageHammerofMightMelee", new Element[]{ Element.Impact }},
            { "Violence", new Element[]{ Element.Impact, Element.Unholy }},
            #endregion
            #endregion

            #region Ranged
            #region Pre-Hardmode
            { "AquashardShotgun", new Element[]{ Element.Stab, Element.Water }},
            { "Archerfish", new Element[]{ Element.Stab, Element.Water }},
            { "Barinade", new Element[]{ Element.Stab, Element.Water }},
            { "BulletFilledShotgun", new Element[]{ Element.Stab }},
            { "CoralCannon", new Element[]{ Element.Stab, Element.Water }},
            { "CrackshotColt", new Element[]{ Element.Stab }},
            { "DragoonDrizzlefish", new Element[]{ Element.Fire }},
            { "Eviscerator", new Element[]{ Element.Stab, Element.Dark }},
            { "FirestormCannon", new Element[]{ Element.Impact, Element.Fire }},
            { "FlurrystormCannon", new Element[]{ Element.Impact, Element.Cold }},
            { "Fungicide", new Element[]{ Element.Stab, Element.Poison }},
            { "Galeforce", new Element[]{ Element.Stab, Element.Holy }},
            { "Goobow", new Element[]{ Element.Stab, Element.Poison }},
            { "GunkShot", new Element[]{ Element.Stab, Element.Poison }},
            { "LunarianBow", new Element[]{ Element.Stab }},
            { "MagnaCannon", new Element[]{ Element.Magic }},
            { "OpalStriker", new Element[]{ Element.Stab, Element.Fire }},
            { "OverloadedBlaster", new Element[]{ Element.Poison }},
            { "Pumpler", new Element[]{ Element.Impact }},
            { "ReedBlowgun", new Element[]{  Element.Water }},
            { "Shadethrower", new Element[]{ Element.Dark }},
            { "Shellshooter", new Element[]{ Element.Impact, Element.Water }},
            { "SparkSpreader", new Element[]{ Element.Fire }},
            { "StormSurge", new Element[]{ Element.Water }},
            { "Taser", new Element[]{ Element.Machine }},
            { "Toxibow", new Element[]{ Element.Stab, Element.Poison }},
            { "WulfrumBlunderbuss", new Element[]{ Element.Stab, Element.Machine }},
            #endregion
            #region Hardmode
            { "AdamantiteParticleAccelerator", new Element[]{ Element.Magic, Element.Machine }},
            { "Animosity", new Element[]{ Element.Stab }},
            { "Arbalest", new Element[]{ Element.Stab }},
            { "ArcNovaDiffuser", new Element[]{ Element.Stab }},
            { "AstralBlaster", new Element[]{ Element.Stab }},
            { "AstralBow", new Element[]{ Element.Stab }},
            { "AuroraBlazer", new Element[]{ Element.Machine, Element.Magic }},
            { "Barinautical", new Element[]{ Element.Stab, Element.Poison }},
            { "BarracudaGun", new Element[]{ Element.Stab }},
            { "BladedgeRailbow", new Element[]{ Element.Stab, Element.Poison }},
            { "BlightSpewer", new Element[]{ Element.Poison, Element.Machine }},
            { "BlossomFlux", new Element[]{ Element.Stab, Element.Poison }},
            { "BrimstoneFury", new Element[]{ Element.Stab, Element.Unholy }},
            { "Butcher", new Element[]{ Element.Stab }},
            { "ClamorRifle", new Element[]{ Element.Water }},
            { "ConferenceCall", new Element[]{ Element.Stab }},
            { "ContinentalGreatbow", new Element[]{ Element.Stab, Element.Fire }},
            { "CorrodedCaustibow", new Element[]{ Element.Stab, Element.Poison }},
            { "VernalBolter", new Element[]{ Element.Stab }},
            { "ThermoclineBlaster", new Element[]{ Element.Fire, Element.Cold }},
            { "DarkechoGreatbow", new Element[]{ Element.Stab, Element.Cold }},
            { "DeadSunsWind", new Element[]{ Element.Dark }},
            { "DeepcoreGK2", new Element[]{ Element.Stab }},
            { "EternalBlizzard", new Element[]{ Element.Stab, Element.Cold }},
            { "FlakKraken", new Element[]{ Element.Stab, Element.Water }},
            { "FlakToxicannon", new Element[]{ Element.Stab, Element.Poison }},
            { "FlarewingBow", new Element[]{ Element.Stab, Element.Fire }},
            { "FrostbiteBlaster", new Element[]{ Element.Stab, Element.Cold }},
            { "GaussRifle", new Element[]{ Element.Stab, Element.Machine }},
            { "HavocsBreath", new Element[]{ Element.Unholy }},
            { "Hellborn", new Element[]{ Element.Fire }},
            { "Helstorm", new Element[]{ Element.Stab, Element.Fire }},
            { "HoarfrostBow", new Element[]{ Element.Stab, Element.Cold }},
            { "Hydra", new Element[]{ Element.Stab }},
            { "Leviatitan", new Element[]{ Element.Stab, Element.Poison }},
            { "Malevolence", new Element[]{ Element.Stab, Element.Poison, Element.Machine }},
            { "MarksmanBow", new Element[]{ Element.Stab }},
            { "MatterModulator", new Element[]{ Element.Stab, Element.Machine }},
            { "Megalodon", new Element[]{ Element.Stab, Element.Water }},
            { "Meowthrower", new Element[]{ Element.Magic }},
            { "MidasPrime", new Element[]{ Element.Stab }},
            { "MineralMortar", new Element[]{ Element.Impact }},
            { "Needler", new Element[]{ Element.Stab, Element.Poison }},
            { "NullificationPistol", new Element[]{ Element.Stab, Element.Machine }},
            { "P90", new Element[]{ Element.Stab }},
            { "PearlGod", new Element[]{ Element.Stab, Element.Machine }},
            { "PestilentDefiler", new Element[]{ Element.Stab, Element.Poison, Element.Machine }},
            { "PlagueTaintedSMG", new Element[]{ Element.Stab, Element.Poison, Element.Machine }},
            { "PolarisParrotfish", new Element[]{ Element.Magic }},
            { "RealmRavager", new Element[]{ Element.Stab, Element.Dark }},
            { "SandstormGun", new Element[]{ Element.Stab, Element.Fire }},
            { "Scorpio", new Element[]{ Element.Impact, Element.Machine }},
            { "SeasSearing", new Element[]{ Element.Impact, Element.Water, Element.Poison }},
            { "Shroomer", new Element[]{ Element.Stab, Element.Poison }},
            { "SlagMagnum", new Element[]{ Element.Stab }},
            { "SpectralstormCannon", new Element[]{ Element.Impact }},
            { "SpeedBlaster", new Element[]{ Element.Impact }},
            { "StarSputter", new Element[]{ Element.Impact, Element.Magic }},
            { "StellarCannon", new Element[]{ Element.Impact, Element.Magic }},
            { "WildfireBloom", new Element[]{ Element.Fire }},
            { "TheBallista", new Element[]{ Element.Stab }},
            { "TheHive", new Element[]{ Element.Impact, Element.Poison, Element.Machine }},
            { "TitaniumRailgun", new Element[]{ Element.Stab, Element.Machine }},
            { "Vortexpopper", new Element[]{ Element.Stab }},
            #endregion
            #region Godseeker
            { "AcesHigh", new Element[]{ Element.Impact }},
            { "Alluvion", new Element[]{ Element.Stab, Element.Water }},
            { "AngelicShotgun", new Element[]{ Element.Stab, Element.Holy }},
            { "AntiMaterielRifle", new Element[]{ Element.Stab }},
            { "ArterialAssault", new Element[]{ Element.Stab, Element.Poison, Element.Dark }},
            { "AstrealDefeat", new Element[]{ Element.Magic, Element.Dark }},
            { "Auralis", new Element[]{ Element.Stab }},
            { "BlissfulBombardier", new Element[]{ Element.Impact, Element.Holy, Element.Fire }},
            { "ChickenCannon", new Element[]{ Element.Impact, Element.Fire }},
            { "ClaretCannon", new Element[]{ Element.Stab, Element.Poison, Element.Dark }},
            { "CleansingBlaze", new Element[]{ Element.Magic, Element.Dark }},
            { "ClockworkBow", new Element[]{ Element.Stab, Element.Machine }},
            { "Condemnation", new Element[]{ Element.Stab, Element.Unholy }},
            { "Contagion", new Element[]{ Element.Stab, Element.Poison }},
            { "CorinthPrime", new Element[]{ Element.Stab, Element.Machine }},
            { "DaemonsFlame", new Element[]{ Element.Stab, Element.Dark }},
            { "Deathwind", new Element[]{ Element.Stab, Element.Magic, Element.Dark }},
            { "Disseminator", new Element[]{ Element.Stab }},
            { "DragonsBreath", new Element[]{ Element.Fire }},
            { "Drataliornus", new Element[]{ Element.Fire }},
            { "ElementalBlaster", new Element[]{ Element.Stab, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "ElementalEruption", new Element[]{ Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "FetidEmesis", new Element[]{ Element.Stab, Element.Poison }},
            { "FreedomStar", new Element[]{ Element.Magic }},
            { "GoldenEagle", new Element[]{ Element.Stab }},
            { "HalibutCannon", new Element[]{ Element.Stab, Element.Water }},
            { "HalleysInferno", new Element[]{ Element.Cold, Element.Dark }},
            { "HandheldTank", new Element[]{ Element.Impact, Element.Machine }},
            { "HeavenlyGale", new Element[]{ Element.Stab, Element.Machine, Element.Fire, Element.Cold }},
            { "HeavyLaserRifle", new Element[]{ Element.Machine }},
            { "Infinity", new Element[]{ Element.Stab }},
            { "Karasawa", new Element[]{ Element.Stab }},
            { "Kingsbane", new Element[]{ Element.Stab, Element.Holy }},
            { "MagnomalyCannon", new Element[]{ Element.Impact, Element.Machine, Element.Fire, Element.Cold }},
            { "MolecularManipulator", new Element[]{ Element.Stab, Element.Machine }},
            { "Monsoon", new Element[]{ Element.Stab, Element.Water }},
            { "NettlevineGreatbow", new Element[]{ Element.Stab, Element.Poison }},
            { "Norfleet", new Element[]{ Element.Magic, Element.Machine }},
            { "OnyxChainBlaster", new Element[]{ Element.Stab, Element.Dark }},
            { "Onyxia", new Element[]{ Element.Stab, Element.Dark }},
            { "Phangasm", new Element[]{ Element.Stab, Element.Machine }},
            { "Photoviscerator", new Element[]{ Element.Magic, Element.Machine, Element.Fire, Element.Cold }},
            { "PlanetaryAnnihilation", new Element[]{ Element.Stab, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "PridefulHuntersPlanarRipper", new Element[]{ Element.Stab, Element.Machine }},
            { "PristineFury", new Element[]{ Element.Holy, Element.Fire }},
            { "PulseRifle", new Element[]{ Element.Machine }},
            { "RubicoPrime", new Element[]{ Element.Stab }},
            { "SDFMG", new Element[]{ Element.Stab, Element.Water }},
            { "ScorchedEarth", new Element[]{ Element.Impact, Element.Machine }},
            { "Seadragon", new Element[]{ Element.Stab, Element.Water }},
            { "SepticSkewer", new Element[]{ Element.Stab, Element.Poison }},
            { "Shredder", new Element[]{ Element.Stab }},
            { "SomaPrime", new Element[]{ Element.Stab, Element.Machine }},
            { "Spyker", new Element[]{ Element.Stab, Element.Poison }},
            { "Starfleet", new Element[]{ Element.Magic }},
            { "Starmada", new Element[]{ Element.Magic, Element.Machine }},
            { "Starmageddon", new Element[]{ Element.Magic }},
            { "StormDragoon", new Element[]{ Element.Stab }},
            { "SulphuricAcidCannon", new Element[]{ Element.Impact, Element.Poison }},
            { "SurgeDriver", new Element[]{ Element.Machine }},
            { "Svantechnical", new Element[]{ Element.Stab }},
            { "TelluricGlare", new Element[]{ Element.Stab, Element.Holy, Element.Fire }},
            { "TheAnomalysNanogun", new Element[]{ Element.Machine }},
            { "TheJailor", new Element[]{ Element.Machine }},
            { "TheMaelstrom", new Element[]{ Element.Stab, Element.Water }},
            { "ThePack", new Element[]{ Element.Impact }},
            { "TheSevensStriker", new Element[]{ Element.Stab }},
            { "TheStorm", new Element[]{ Element.Stab }},
            { "TyrannysEnd", new Element[]{ Element.Stab }},
            { "Ultima", new Element[]{ Element.Stab }},
            { "UniversalGenesis", new Element[]{ Element.Stab, Element.Magic }},
            { "Voidragon", new Element[]{ Element.Stab, Element.Dark }},
            #endregion
            #endregion

            #region Magic
            #region Pre-Hardmode
            { "AbyssShocker", new Element[]{ Element.Water }},
            { "AbyssalTome", new Element[]{ Element.Poison }},
            { "AcidGun", new Element[]{ Element.Poison }},
            { "AquamarineStaff", new Element[]{ Element.Water }},
            { "BlackAnurian", new Element[]{ Element.Poison }},
            { "BloodBath", new Element[]{ Element.Dark }},
            { "CoralSpout", new Element[]{ Element.Water }},
            { "EldritchTome", new Element[]{ Element.Poison}},
            { "FlareBolt", new Element[]{ Element.Fire }},
            { "FrostBolt", new Element[]{ Element.Cold }},
            { "HarvestStaff", new Element[]{ Element.Fire }},
            { "HellwingStaff", new Element[]{ Element.Fire }},
            { "HyphaeRod", new Element[]{ Element.Poison }},
            { "IcicleStaff", new Element[]{ Element.Cold }},
            { "ManaRose", new Element[]{ Element.Magic }},
            { "NightsRay", new Element[]{ Element.Dark }},
            { "ParasiticSceptor", new Element[]{ Element.Poison }},
            { "PlasmaRod", new Element[]{ Element.Dark }},
            { "PulsePistol", new Element[]{ Element.Machine }},
            { "SandstreamScepter", new Element[]{ Element.Fire }},
            { "ShaderainStaff", new Element[]{ Element.Dark }},
            { "SkyGlaze", new Element[]{ Element.Holy }},
            { "SparklingEmpress", new Element[]{ Element.Water }},
            { "Tradewinds", new Element[]{ Element.Holy }},
            { "VeeringWind", new Element[]{ Element.Cold }},
            { "Waywasher", new Element[]{ Element.Water }},
            { "WulfrumProsthesis", new Element[]{ Element.Machine }},
            #endregion
            #region Hardmode
            { "AlulaAustralis", new Element[]{ Element.Machine, Element.Magic }},
            { "AnahitasArpeggio", new Element[]{ Element.Water }},
            { "ArchAmaryllis", new Element[]{ Element.Magic }},
            { "ArcticBearPaw", new Element[]{ Element.Cold }},
            { "ArtAttack", new Element[]{ Element.Magic }},
            { "AstralStaff", new Element[]{ Element.Magic }},
            { "AstralachneaStaff", new Element[]{ Element.Magic }},
            { "Atlantis", new Element[]{ Element.Water }},
            { "BelchingSaxophone", new Element[]{ Element.Poison }},
            { "BrimroseStaff", new Element[]{ Element.Unholy }},
            { "BurningSea", new Element[]{ Element.Unholy }},
            { "ClothiersWrath", new Element[]{ Element.Dark }},
            { "CosmicRainbow", new Element[]{ Element.Holy }},
            { "Cryophobia", new Element[]{ Element.Cold }},
            { "DeathValleyDuster", new Element[]{ Element.Magic }},
            { "Downpour", new Element[]{ Element.Water }},
            { "EvergladeSpray", new Element[]{ Element.Poison }},
            { "ForbiddenSun", new Element[]{ Element.Fire }},
            { "FrigidflashBolt", new Element[]{ Element.Cold, Element.Fire }},
            { "GatlingLaser", new Element[]{ Element.Machine }},
            { "GaussPistol", new Element[]{ Element.Machine }},
            { "GleamingMagnolia", new Element[]{ Element.Magic }},
            { "GloriousEnd", new Element[]{ Element.Magic }},
            { "HadalUrn", new Element[]{ Element.Water }},
            { "Hematemesis", new Element[]{ Element.Poison }},
            { "IcicleTrident", new Element[]{ Element.Cold }},
            { "InfernalRift", new Element[]{ Element.Fire }},
            { "IonBlaster", new Element[]{ Element.Magic }},
            { "Keelhaul", new Element[]{ Element.Water }},
            { "LashesofChaos", new Element[]{ Element.Unholy, Element.Fire }},
            { "Lazhar", new Element[]{ Element.Magic }},
            { "Miasma", new Element[]{ Element.Poison }},
            { "NanoPurge", new Element[]{ Element.Machine }},
            { "PlagueStaff", new Element[]{ Element.Poison, Element.Machine }},
            { "Poseidon", new Element[]{ Element.Water }},
            { "PrimordialEarth", new Element[]{ Element.Magic }},
            { "RelicofRuin", new Element[]{ Element.Magic }},
            { "SHPC", new Element[]{ Element.Machine }},
            { "SeethingDischarge", new Element[]{ Element.Unholy }},
            { "Serpentine", new Element[]{ Element.Water }},
            { "ShadecrystalBarrage", new Element[]{ Element.Cold }},
            { "ShiftingSands", new Element[]{ Element.Magic }},
            { "SlitheringEels", new Element[]{ Element.Poison }},
            { "SnowstormStaff", new Element[]{ Element.Cold }},
            { "StarShower", new Element[]{ Element.Magic }},
            { "TearsofHeaven", new Element[]{ Element.Holy }},
            { "Photosynthesis", new Element[]{ Element.Magic }},
            { "TheSwarmer", new Element[]{ Element.Poison }},
            { "TomeofFates", new Element[]{ Element.Dark }},
            { "UndinesRetribution", new Element[]{ Element.Water }},
            { "ValkyrieRay", new Element[]{ Element.Holy }},
            { "Vesuvius", new Element[]{ Element.Fire }},
            { "Wingman", new Element[]{ Element.Machine }},
            { "WintersFury", new Element[]{ Element.Cold }},
            { "WrathoftheAncients", new Element[]{ Element.Magic }},
            { "WyvernsCall", new Element[]{ Element.Magic }},
            #endregion
            #region Godseeker
            { "AethersWhisper", new Element[]{ Element.Dark }},
            { "AetherfluxCannon", new Element[]{ Element.Holy }},
            { "Omicron", new Element[]{ Element.Machine }},
            { "ApoctosisArray", new Element[]{ Element.Magic }},
            { "Apotheosis", new Element[]{ Element.Magic, Element.Dark }},
            { "AsteroidStaff", new Element[]{ Element.Magic }},
            { "AuguroftheElements", new Element[]{ Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "Biofusillade", new Element[]{ Element.Poison }},
            { "ClamorNoctus", new Element[]{ Element.Cold, Element.Dark }},
            { "DarkSpark", new Element[]{ Element.Dark }},
            { "DeathhailStaff", new Element[]{ Element.Magic, Element.Dark }},
            { "Effervescence", new Element[]{ Element.Water }},
            { "EidolicWail", new Element[]{ Element.Water }},
            { "EidolonStaff", new Element[]{ Element.Magic, Element.Cold }},
            { "ElementalRay", new Element[]{ Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "Eternity", new Element[]{ Element.Magic }},
            { "EventHorizon", new Element[]{ Element.Holy, Element.Dark }},
            { "FaceMelter", new Element[]{ Element.Machine }},
            { "FatesReveal", new Element[]{ Element.Dark }},
            { "Genesis", new Element[]{ Element.Machine }},
            { "GhastlyVisage", new Element[]{ Element.Dark }},
            { "GruesomeEminence", new Element[]{ Element.Unholy }},
            { "HeliumFlash", new Element[]{ Element.Fire }},
            { "Heresy", new Element[]{ Element.Unholy }},
            { "IceBarrage", new Element[]{ Element.Cold }},
            { "LightGodsBrilliance", new Element[]{ Element.Holy }},
            { "MadAlchemistsCocktailGlove", new Element[]{ Element.Poison }},
            { "MagneticMeltdown", new Element[]{ Element.Magic, Element.Machine }},
            { "Mistlestorm", new Element[]{ Element.Poison }},
            { "NebulousCataclysm", new Element[]{ Element.Magic }},
            { "NuclearFury", new Element[]{ Element.Water }},
            { "PhantasmalFury", new Element[]{ Element.Dark }},
            { "PhoenixFlameBarrage", new Element[]{ Element.Fire }},
            { "PlasmaCaster", new Element[]{ Element.Machine }},
            { "PlasmaRifle", new Element[]{ Element.Machine }},
            { "PrimordialAncient", new Element[]{ Element.Magic }},
            { "PurgeGuzzler", new Element[]{ Element.Holy, Element.Fire }},
            { "RainbowPartyCannon", new Element[]{ Element.Magic }},
            { "Rancor", new Element[]{ Element.Unholy }},
            { "RecitationoftheBeast", new Element[]{ Element.Unholy }},
            { "RougeSlash", new Element[]{ Element.Magic }},
            { "SanguineFlare", new Element[]{ Element.Poison }},
            { "ShadowboltStaff", new Element[]{ Element.Dark }},
            { "SoulPiercer", new Element[]{ Element.Magic, Element.Dark }},
            { "StaffofBlushie", new Element[]{ Element.Magic }},
            { "SubsumingVortex", new Element[]{ Element.Magic, Element.Machine, Element.Fire, Element.Cold }},
            { "Sylvestaff", new Element[]{ Element.Magic, Element.Machine }},
            { "TacticiansTrumpCard", new Element[]{ Element.Magic }},
            { "TeslaCannon", new Element[]{ Element.Machine }},
            { "TheDanceofLight", new Element[]{ Element.Holy }},
            { "ThePrince", new Element[]{ Element.Holy, Element.Fire }},
            { "TheWand", new Element[]{ Element.Fire }},
            { "ThornBlossom", new Element[]{ Element.Magic, Element.Poison }},
            { "Thunderstorm", new Element[]{ Element.Magic }},
            { "UltraLiquidator", new Element[]{ Element.Magic }},
            { "Vehemence", new Element[]{ Element.Unholy }},
            { "VenusianTrident", new Element[]{ Element.Fire }},
            { "Viscera", new Element[]{ Element.Poison }},
            { "VitriolicViper", new Element[]{ Element.Poison }},
            { "VividClarity", new Element[]{ Element.Magic, Element.Machine, Element.Fire, Element.Cold }},
            { "VoidVortex", new Element[]{ Element.Magic, Element.Machine }},
            { "VoltaicClimax", new Element[]{ Element.Magic, Element.Machine }},
            { "YharimsCrystal", new Element[]{ Element.Holy }},
            #endregion
            #endregion

            #region Summon
            #region Pre-Hardmode
            { "BelladonnaSpiritStaff", new Element[]{ Element.Poison }},
            { "BrittleStarStaff", new Element[]{ Element.Impact }},
            { "CausticCroakerStaff", new Element[]{ Element.Impact, Element.Poison }},
            { "CinderBlossomStaff", new Element[]{ Element.Fire }},
            { "Cnidarian", new Element[]{ Element.Impact, Element.Water }},
            { "CorroslimeStaff", new Element[]{ Element.Impact, Element.Poison }},
            { "CrimslimeStaff", new Element[]{ Element.Impact, Element.Poison }},
            { "DankStaff", new Element[]{ Element.Impact, Element.Dark }},
            { "DeathstareRod", new Element[]{ Element.Dark }},
            { "EnchantedConch", new Element[]{ Element.Impact }},
            { "EyeOfNight", new Element[]{ Element.Dark }},
            { "FleshOfInfidelity", new Element[]{ Element.Impact, Element.Dark }},
            { "FrostBlossomStaff", new Element[]{ Element.Cold }},
            { "HerringStaff", new Element[]{ Element.Impact, Element.Water }},
            { "PolypLauncher", new Element[]{ Element.Water }},
            { "PuffShroom", new Element[]{ Element.Impact, Element.Poison }},
            { "RustyBeaconPrototype", new Element[]{ Element.Machine, Element.Poison }},
            { "ScabRipper", new Element[]{ Element.Impact, Element.Dark }},
            { "SlimePuppetStaff", new Element[]{ Element.Impact, Element.Poison }},
            { "SquirrelSquireStaff", new Element[]{ Element.Magic }},
            { "StaffOfNecrosteocytes", new Element[]{ Element.Impact, Element.Dark }},
            { "StarSwallowerContainmentUnit", new Element[]{ Element.Machine }},
            { "StormjawStaff", new Element[]{ Element.Impact }},
            { "SunSpiritStaff", new Element[]{ Element.Holy }},
            { "VileFeeder", new Element[]{ Element.Impact, Element.Dark }},
            { "WulfrumController", new Element[]{ Element.Machine }},
            #endregion
            #region Hardmode
            { "AbandonedSlimeStaff", new Element[]{ Element.Impact, Element.Magic }},
            { "AncientIceChunk", new Element[]{ Element.Impact, Element.Cold }},
            { "BlackHawkRemote", new Element[]{ Element.Machine }},
            { "BorealisBomber", new Element[]{ Element.Impact, Element.Machine, Element.Magic }},
            { "CausticStaff", new Element[]{ Element.Poison }},
            { "CryogenicStaff", new Element[]{ Element.Cold }},
            { "DaedalusGolemStaff", new Element[]{ Element.Machine, Element.Cold }},
            { "DeepseaStaff", new Element[]{ Element.Impact, Element.Water, Element.Poison }},
            { "DormantBrimseeker", new Element[]{ Element.Unholy }},
            { "DreadmineStaff", new Element[]{ Element.Water }},
            { "EntropysVigil", new Element[]{ Element.Impact, Element.Unholy }},
            { "ForgottenApexWand", new Element[]{ Element.Impact }},
            { "FuelCellBundle", new Element[]{ Element.Poison, Element.Machine }},
            { "GastricBelcherStaff", new Element[]{ Element.Poison }},
            { "GlacialEmbrace", new Element[]{ Element.Cold }},
            { "HauntedScroll", new Element[]{ Element.Impact }},
            { "HivePod", new Element[]{  Element.Magic }},
            { "IgneousExaltation", new Element[]{ Element.Stab, Element.Unholy }},
            { "InfectedRemote", new Element[]{ Element.Poison, Element.Machine }},
            { "MountedScanner", new Element[]{ Element.Machine }},
            { "OrthoceraShell", new Element[]{ Element.Poison }},
            { "PlantationStaff", new Element[]{ Element.Poison }},
            { "PulseTurretRemote", new Element[]{ Element.Machine }},
            { "ResurrectionButterfly", new Element[]{ Element.Magic }},
            { "SandSharknadoStaff", new Element[]{ Element.Fire }},
            { "ShellfishStaff", new Element[]{ Element.Impact, Element.Water }},
            { "SpikecragStaff", new Element[]{ Element.Dark }},
            { "StarspawnHelixStaff", new Element[]{ Element.Slash, Element.Machine, Element.Magic }},
            { "TundraFlameBlossomsStaff", new Element[]{ Element.Cold, Element.Fire }},
            { "VengefulSunStaff", new Element[]{ Element.Holy }},
            { "ViralSprout", new Element[]{ Element.Poison }},
            { "WitherBlossomsStaff", new Element[]{ Element.Poison, Element.Machine }},
            #endregion
            #region Godseeker
            { "AquasScepter", new Element[]{ Element.Water }},
            { "AresExoskeleton", new Element[]{ Element.Machine }},
            { "AtlasMunitionsBeacon", new Element[]{ Element.Machine }},
            { "CadaverousCarrion", new Element[]{ Element.Poison }},
            { "CalamarisLament", new Element[]{ Element.Water }},
            { "CindersOfLament", new Element[]{ Element.Impact, Element.Unholy }},
            { "CorvidHarbringerStaff", new Element[]{ Element.Impact, Element.Dark }},
            { "CosmicImmaterializer", new Element[]{ Element.Magic, Element.Machine, Element.Fire, Element.Cold }},
            { "CosmicViperEngine", new Element[]{ Element.Machine, Element.Magic, Element.Dark }},
            { "Cosmilamp", new Element[]{ Element.Magic, Element.Dark }},
            { "DazzlingStabberStaff", new Element[]{ Element.Stab, Element.Holy, Element.Fire }},
            { "DragonbloodDisgorger", new Element[]{ Element.Poison, Element.Dark }},
            { "ElementalAxe", new Element[]{ Element.Slash, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "EndoHydraStaff", new Element[]{ Element.Cold }},
            { "Endogenesis", new Element[]{ Element.Cold }},
            { "EtherealSubjugator", new Element[]{ Element.Cold, Element.Dark }},
            { "FlamsteedRing", new Element[]{ Element.Machine }},
            { "FlowersOfMortality", new Element[]{ Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "GammaHeart", new Element[]{ Element.Poison }},
            { "GuidelightofOblivion", new Element[]{ Element.Fire, Element.Dark }},
            { "KingofConstellationsTenryu", new Element[]{ Element.Impact, Element.Fire }},
            { "Metastasis", new Element[]{ Element.Impact, Element.Unholy }},
            { "MidnightSunBeacon", new Element[]{ Element.Machine }},
            { "MirrorofKalandra", new Element[]{ Element.Holy }},
            { "MutatedTruffle", new Element[]{ Element.Impact, Element.Poison }},
            { "Perdition", new Element[]{ Element.Unholy }},
            { "SanctifiedSpark", new Element[]{ Element.Holy, Element.Fire }},
            { "SarosPossession", new Element[]{ Element.Holy, Element.Dark }},
            { "Sirius", new Element[]{ Element.Cold, Element.Dark }},
            { "SnakeEyes", new Element[]{ Element.Machine }},
            { "StaffoftheMechworm", new Element[]{ Element.Machine, Element.Magic, Element.Dark }},
            { "StellarTorusStaff", new Element[]{ Element.Magic }},
            { "TacticalPlagueEngine", new Element[]{ Element.Poison, Element.Machine }},
            { "TemporalUmbrella", new Element[]{ Element.Magic }},
            { "UniverseSplitter", new Element[]{ Element.Machine }},
            { "Vigilance", new Element[]{ Element.Unholy }},
            { "ViridVanguard", new Element[]{ Element.Slash, Element.Poison }},
            { "VoidConcentrationStaff", new Element[]{ Element.Dark }},
            { "WarloksMoonFist", new Element[]{ Element.Impact, Element.Magic }},
            { "YharonsKindleStaff", new Element[]{ Element.Fire }},
            #endregion
            #endregion
            
            #region Rogue
            #region Pre-Hardmode
            { "AshenStalactite", new Element[]{ Element.Stab }},
            { "BouncingEyeball", new Element[]{ Element.Impact, Element.Dark }},
            { "BouncySpikyBall", new Element[]{ Element.Stab, Element.Poison }},
            { "Cinquedea", new Element[]{ Element.Stab }},
            { "ContaminatedBile", new Element[]{ Element.Poison }},
            { "Crystalline", new Element[]{ Element.Stab }},
            { "EnchantedAxe", new Element[]{ Element.Slash, Element.Magic }},
            { "FeatherKnife", new Element[]{ Element.Stab, Element.Holy }},
            { "FishboneBoomerang", new Element[]{ Element.Impact, Element.Water }},
            { "GelDart", new Element[]{ Element.Stab, Element.Poison }},
            { "GildedDagger", new Element[]{ Element.Stab }},
            { "Glaive", new Element[]{ Element.Slash }},
            { "GleamingDagger", new Element[]{ Element.Stab }},
            { "HardenedHoneycomb", new Element[]{ Element.Impact }},
            { "InfernalKris", new Element[]{ Element.Stab, Element.Fire }},
            { "InfestedClawmerang", new Element[]{ Element.Impact, Element.Poison }},
            { "IronFrancisca", new Element[]{ Element.Slash }},
            { "Lionfish", new Element[]{ Element.Stab, Element.Poison }},
            { "MetalMonstrosity", new Element[]{ Element.Stab }},
            { "MeteorFist", new Element[]{ Element.Impact, Element.Fire }},
            { "Mycoroot", new Element[]{ Element.Impact, Element.Poison }},
            { "NastyCholla", new Element[]{ Element.Stab, Element.Poison }},
            { "PoisonPack", new Element[]{ Element.Stab, Element.Poison }},
            { "RotBall", new Element[]{ Element.Stab, Element.Dark }},
            { "SandDollar", new Element[]{ Element.Impact, Element.Water }},
            { "ScourgeoftheDesert", new Element[]{ Element.Stab, Element.Fire }},
            { "SeafoamBomb", new Element[]{ Element.Impact, Element.Water }},
            { "ShinobiBlade", new Element[]{ Element.Stab }},
            { "SkyStabber", new Element[]{ Element.Stab, Element.Holy }},
            { "SludgeSplotch", new Element[]{ Element.Impact, Element.Poison }},
            { "SnapClam", new Element[]{ Element.Impact, Element.Water }},
            { "StickySpikyBall", new Element[]{ Element.Stab, Element.Poison }},
            { "ThrowingBrick", new Element[]{ Element.Impact }},
            { "ToothBall", new Element[]{ Element.Stab, Element.Dark }},
            { "TrackingDisk", new Element[]{ Element.Machine }},
            { "Turbulance", new Element[]{ Element.Stab, Element.Holy }},
            { "UrchinStinger", new Element[]{ Element.Stab, Element.Poison }},
            { "WebBall", new Element[]{ Element.Impact }},
            { "WulfrumKnife", new Element[]{ Element.Stab, Element.Machine }},
            #endregion
            #region Hardmode
            { "AcidicRainBarrel", new Element[]{ Element.Impact, Element.Poison }},
            { "AdamantiteThrowingAxe", new Element[]{ Element.Slash }},
            { "Apoctolith", new Element[]{ Element.Impact, Element.Water }},
            { "AuroradicalThrow", new Element[]{ Element.Slash, Element.Machine, Element.Magic }},
            { "BallisticPoisonBomb", new Element[]{ Element.Impact, Element.Poison }},
            { "BlastBarrel", new Element[]{ Element.Impact, Element.Fire }},
            { "BlazingStar", new Element[]{ Element.Slash, Element.Fire }},
            { "BrackishFlask", new Element[]{ Element.Poison }},
            { "Brimblade", new Element[]{ Element.Slash, Element.Unholy }},
            { "BurningStrife", new Element[]{ Element.Stab, Element.Dark }},
            { "CobaltKunai", new Element[]{ Element.Stab }},
            { "ConsecratedWater", new Element[]{ Element.Water, Element.Holy }},
            { "CorpusAvertor", new Element[]{ Element.Stab, Element.Dark }},
            { "CraniumSmasher", new Element[]{ Element.Impact, Element.Dark }},
            { "CrushsawCrasher", new Element[]{ Element.Impact, Element.Unholy }},
            { "CrystalPiercer", new Element[]{ Element.Stab, Element.Cold }},
            { "CursedDagger", new Element[]{ Element.Stab, Element.Fire }},
            { "DeepWounder", new Element[]{ Element.Slash, Element.Water }},
            { "DefectiveSphere", new Element[]{ Element.Stab, Element.Machine }},
            { "DesecratedWater", new Element[]{ Element.Water, Element.Dark }},
            { "DukesDecapitator", new Element[]{ Element.Slash, Element.Water }},
            { "DuststormInABottle", new Element[]{ Element.Fire }},
            { "EpidemicShredder", new Element[]{ Element.Slash, Element.Poison, Element.Machine }},
            { "Equanimity", new Element[]{ Element.Impact }},
            { "Exorcism", new Element[]{ Element.Impact, Element.Holy }},
            { "FantasyTalisman", new Element[]{ Element.Dark }},
            { "FrequencyManipulator", new Element[]{ Element.Stab, Element.Machine }},
            { "FrostcrushValari", new Element[]{ Element.Impact, Element.Cold }},
            { "FrostyFlare", new Element[]{ Element.Cold }},
            { "GacruxianMollusk", new Element[]{ Element.Machine, Element.Magic }},
            { "GraveGrimreaver", new Element[]{ Element.Slash, Element.Dark }},
            { "HeavenfallenStardisk", new Element[]{ Element.Slash, Element.Magic }},
            { "IceStar", new Element[]{ Element.Slash, Element.Cold }},
            { "Icebreaker", new Element[]{ Element.Impact, Element.Cold }},
            { "IchorSpear", new Element[]{ Element.Stab, Element.Dark }},
            { "KelvinCatalyst", new Element[]{ Element.Slash, Element.Cold }},
            { "LeonidProgenitor", new Element[]{ Element.Magic }},
            { "LeviathanTeeth", new Element[]{ Element.Stab, Element.Poison }},
            { "Malachite", new Element[]{ Element.Stab }},
            { "MangroveChakram", new Element[]{ Element.Slash, Element.Poison }},
            { "MonkeyDarts", new Element[]{ Element.Stab }},
            { "MythrilKnife", new Element[]{ Element.Stab }},
            { "Nychthemeron", new Element[]{ Element.Stab }},
            { "OrichalcumSpikedGemstone", new Element[]{ Element.Stab }},
            { "PalladiumJavelin", new Element[]{ Element.Stab }},
            { "PhantasmalRuin", new Element[]{ Element.Stab, Element.Dark }},
            { "Plaguenade", new Element[]{ Element.Impact, Element.Poison, Element.Machine }},
            { "Prismalline", new Element[]{ Element.Stab, Element.Water }},
            { "RadiantStar", new Element[]{ Element.Stab, Element.Magic }},
            { "RegulusRiot", new Element[]{ Element.Slash, Element.Magic }},
            { "Sandslasher", new Element[]{ Element.Slash }},
            { "ScourgeoftheSeas", new Element[]{ Element.Stab, Element.Water, Element.Poison }},
            { "ShardofAntumbra", new Element[]{ Element.Stab, Element.Dark }},
            { "ShockGrenade", new Element[]{ Element.Impact, Element.Machine }},
            { "SkyfinBombers", new Element[]{ Element.Impact, Element.Poison }},
            { "SlickCane", new Element[]{ Element.Slash }},
            { "SpearofDestiny", new Element[]{ Element.Stab }},
            { "SpearofPaleolith", new Element[]{ Element.Stab }},
            { "SpentFuelContainer", new Element[]{ Element.Poison }},
            { "StarofDestruction", new Element[]{ Element.Slash, Element.Dark }},
            { "StellarKnife", new Element[]{ Element.Stab, Element.Magic }},
            { "StormfrontRazor", new Element[]{ Element.Stab }},
            { "SubductionSlicer", new Element[]{ Element.Slash, Element.Fire }},
            { "SystemBane", new Element[]{ Element.Impact, Element.Machine }},
            { "SamsaraSlicer", new Element[]{ Element.Slash }},
            { "TerrorTalons", new Element[]{ Element.Slash }},
            { "TitaniumShuriken", new Element[]{ Element.Slash }},
            { "TotalityBreakers", new Element[]{ Element.Impact, Element.Fire }},
            { "WaveSkipper", new Element[]{ Element.Stab, Element.Water }},
            #endregion
            #region Godseeker
            { "AlphaVirus", new Element[]{ Element.Impact, Element.Poison, Element.Machine }},
            { "BloodsoakedCrasher", new Element[]{ Element.Slash, Element.Poison, Element.Dark }},
            { "CelestialReaper", new Element[]{ Element.Slash, Element.Magic }},
            { "Celestus", new Element[]{ Element.Slash, Element.Machine, Element.Fire, Element.Cold }},
            { "CosmicKunai", new Element[]{ Element.Stab, Element.Dark }},
            { "DeepSeaDumbbell", new Element[]{ Element.Impact, Element.Water }},
            { "DynamicPursuer", new Element[]{ Element.Machine }},
            { "EclipsesFall", new Element[]{ Element.Holy, Element.Dark }},
            { "ElementalDisk", new Element[]{ Element.Slash, Element.Fire, Element.Magic, Element.Poison, Element.Cold }},
            { "Eradicator", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "ExecutionersBlade", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "GhoulishGouger", new Element[]{ Element.Slash, Element.Dark }},
            { "GodsParanoia", new Element[]{ Element.Stab, Element.Magic, Element.Dark }},
            { "HellsSun", new Element[]{ Element.Stab, Element.Holy, Element.Fire }},
            { "Hypothermia", new Element[]{ Element.Stab, Element.Cold }},
            { "JawsOfOblivion", new Element[]{ Element.Stab, Element.Water }},
            { "LunarKunai", new Element[]{ Element.Stab }},
            { "MoltenAmputator", new Element[]{ Element.Slash, Element.Holy, Element.Fire }},
            { "NanoblackReaper", new Element[]{ Element.Slash, Element.Machine, Element.Dark }},
            { "NightsGaze", new Element[]{ Element.Stab, Element.Cold, Element.Dark }},
            { "Penumbra", new Element[]{ Element.Dark }},
            { "PlasmaGrenade", new Element[]{ Element.Machine }},
            { "ProfanedPartisan", new Element[]{ Element.Stab, Element.Holy, Element.Fire }},
            { "RealityRupture", new Element[]{ Element.Stab, Element.Dark }},
            { "RefractionRotor", new Element[]{ Element.Slash, Element.Machine }},
            { "Sacrifice", new Element[]{ Element.Stab, Element.Unholy }},
            { "ScarletDevil", new Element[]{ Element.Stab, Element.Unholy }},
            { "SealedSingularity", new Element[]{ Element.Dark }},
            { "SearedPan", new Element[]{ Element.Impact, Element.Fire }},
            { "Seraphim", new Element[]{ Element.Stab, Element.Holy }},
            { "ShatteredSun", new Element[]{ Element.Stab, Element.Holy, Element.Fire }},
            { "Supernova", new Element[]{ Element.Impact, Element.Machine, Element.Fire, Element.Cold }},
            { "TarragonThrowingDart", new Element[]{ Element.Stab, Element.Poison, Element.Holy }},
            { "TheAtomSplitter", new Element[]{ Element.Stab, Element.Machine }},
            { "TheFinalDawn", new Element[]{ Element.Slash, Element.Fire }},
            { "TheOldReaper", new Element[]{ Element.Slash, Element.Poison }},
            { "TimeBolt", new Element[]{ Element.Stab }},
            { "ToxicantTwister", new Element[]{ Element.Slash, Element.Poison }},
            { "TwistingThunder", new Element[]{ Element.Machine }},
            { "UtensilPoker", new Element[]{ Element.Stab }},
            { "Valediction", new Element[]{ Element.Impact, Element.Water }},
            { "WavePounder", new Element[]{ Element.Impact, Element.Machine }},
            { "Wrathwing", new Element[]{ Element.Stab, Element.Fire }},
            #endregion
            #endregion

            #region Classless
            #region Pre-Hardmode
            { "Aestheticus", new Element[]{ Element.Magic }},
            { "Skynamite", new Element[]{ Element.Impact, Element.Holy }},
            #endregion
            #region Hardmode
            { "EyeofMagnus", new Element[]{ Element.Magic }},
            { "LunicEye", new Element[]{ Element.Dark }},
            { "StarStruckWater", new Element[]{ Element.Water, Element.Magic }},
            #endregion
            #region Godseeker
            { "RelicOfDeliverance", new Element[]{ Element.Stab, Element.Holy, Element.Fire }},
            #endregion
            #endregion
        };
        // Vulnerable - Resistant
        internal static Dictionary<string, Tuple<Element[], Element[]>> Bosses = new()
        {
            #region Pre-Hardmode
            { "DesertScourgeHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Water }, new Element[]{ Element.Fire }) },
            { "DesertScourgeBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash, Element.Water }, new Element[]{ Element.Fire }) },
            { "DesertScourgeTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash, Element.Water }, new Element[]{ Element.Fire }) },
            { "Crabulon", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Machine }, new Element[]{ Element.Water, Element.Poison }) },
            { "HiveMind", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Impact }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorHive", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire, Element.Impact }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorHeadLarge", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorHeadMedium", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorHeadSmall", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorBodyLarge", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorBodyMedium", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorBodySmall", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorTailLarge", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorTailMedium", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "PerforatorTailSmall", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Fire }, new Element[]{ Element.Unholy, Element.Dark }) },
            { "SlimeGodCore", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Water, Element.Stab, Element.Machine }, new Element[]{ Element.Unholy, Element.Poison, Element.Slash }) },
            { "CrimulanPaladin", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Water, Element.Stab, Element.Machine }, new Element[]{ Element.Unholy, Element.Poison, Element.Slash }) },
            { "SplitCrimulanPaladin", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Water, Element.Stab, Element.Machine }, new Element[]{ Element.Unholy, Element.Poison, Element.Slash }) },
            { "EbonianPaladin", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Water, Element.Stab, Element.Machine }, new Element[]{ Element.Unholy, Element.Poison, Element.Slash }) },
            { "SplitEbonianPaladin", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy, Element.Water, Element.Stab, Element.Machine }, new Element[]{ Element.Unholy, Element.Poison, Element.Slash }) },
            #endregion
            #region Hardmode
            { "Cryogen", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Impact, Element.Unholy }, new Element[]{ Element.Cold, Element.Water, Element.Magic, Element.Slash }) },
            { "BrimstoneElemental", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Machine }, new Element[]{ Element.Unholy, Element.Fire, Element.Cold }) },
            { "AquaticScourgeHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash, Element.Stab, Element.Cold }, new Element[]{ Element.Water, Element.Poison, Element.Fire }) },
            { "AquaticScourgeBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash, Element.Stab, Element.Cold }, new Element[]{ Element.Water, Element.Poison, Element.Fire }) },
            { "AquaticScourgeBodyAlt", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash, Element.Stab, Element.Cold }, new Element[]{ Element.Water, Element.Poison, Element.Fire }) },
            { "AquaticScourgeTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash, Element.Stab, Element.Cold }, new Element[]{ Element.Water, Element.Poison, Element.Fire }) },
            { "CalamitasClone", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy }, new Element[]{ Element.Fire, Element.Unholy, Element.Magic, Element.Slash }) },
            { "Catastrophe", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Stab }, new Element[]{ Element.Fire, Element.Unholy, Element.Magic, Element.Slash }) },
            { "Cataclysm", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Slash }, new Element[]{ Element.Fire, Element.Unholy, Element.Magic, Element.Stab }) },
            { "Leviathan", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Stab, Element.Unholy, Element.Machine }, new Element[]{ Element.Water, Element.Cold, Element.Dark }) },
            { "Anahita", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Stab, Element.Unholy, Element.Machine, Element.Poison }, new Element[]{ Element.Water, Element.Cold }) },
            { "AstrumAureus", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Fire, Element.Stab }, new Element[]{ Element.Poison, Element.Magic, Element.Slash, Element.Machine }) },
            { "PlaguebringerGoliath", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Fire }, new Element[]{ Element.Poison, Element.Machine, Element.Dark, Element.Slash }) },
            { "RavagerHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Cold }) },
            { "RavagerClawLeft", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Cold }) },
            { "RavagerClawRight", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Cold }) },
            { "RavagerLegLeft", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Cold }) },
            { "RavagerLegRight", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Cold }) },
            { "RavagerBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Cold }) },
            { "AstrumDeusHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Cold, Element.Unholy, Element.Slash, Element.Stab }, new Element[]{ Element.Poison, Element.Magic, Element.Dark, Element.Holy }) },
            { "AstrumDeusBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Cold, Element.Unholy, Element.Slash, Element.Stab }, new Element[]{ Element.Poison, Element.Magic, Element.Dark, Element.Holy }) },
            { "AstrumDeusTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Cold, Element.Unholy, Element.Slash, Element.Stab }, new Element[]{ Element.Poison, Element.Magic, Element.Dark, Element.Holy }) },
            #endregion
            #region Godseeker
            { "ProfanedGuardianCommander", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Unholy, Element.Impact, Element.Machine }, new Element[]{ Element.Holy, Element.Fire, Element.Dark }) },
            { "ProfanedGuardianDefender", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Unholy, Element.Impact, Element.Machine }, new Element[]{ Element.Holy, Element.Fire, Element.Dark }) },
            { "ProfanedGuardianHealer", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Unholy, Element.Impact, Element.Machine }, new Element[]{ Element.Holy, Element.Fire, Element.Dark }) },
            { "Providence", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Unholy, Element.Machine }, new Element[]{ Element.Holy, Element.Fire, Element.Dark }) },
            { "Bumblefuck", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Dark, Element.Poison }, new Element[]{ Element.Holy, Element.Fire }) },
            { "CeaselessVoid", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash }, new Element[]{ Element.Magic, Element.Dark }) },
            { "StormWeaverHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab }, new Element[]{ Element.Magic, Element.Cold, Element.Water }) },
            { "StormWeaverBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab }, new Element[]{ Element.Magic, Element.Cold, Element.Water }) },
            { "StormWeaverTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab }, new Element[]{ Element.Magic, Element.Cold, Element.Water }) },
            { "Signus", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash ,Element.Cold }, new Element[]{ Element.Magic, Element.Dark, Element.Fire }) },
            { "Polterghast", new Tuple<Element[], Element[]>(new Element[]{ Element.Holy ,Element.Slash }, new Element[]{ Element.Dark, Element.Cold, Element.Poison }) },
            { "DevourerofGodsHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash }, new Element[]{ Element.Magic, Element.Poison, Element.Dark }) },
            { "DevourerofGodsBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Slash }, new Element[]{ Element.Magic, Element.Poison, Element.Dark }) },
            { "DevourerofGodsTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Impact }, new Element[]{ Element.Magic, Element.Poison, Element.Dark }) },
            { "Yharon", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Dark, Element.Poison }, new Element[]{ Element.Holy, Element.Fire }) },
            { "AresBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Cold, Element.Poison, Element.Slash, Element.Machine }) },
            { "AresGaussNuke", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Cold, Element.Poison, Element.Slash, Element.Machine }) },
            { "AresLaserCannon", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Cold, Element.Poison, Element.Slash, Element.Machine }) },
            { "AresPlasmaFlamethrower", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Cold, Element.Poison, Element.Slash, Element.Machine }) },
            { "AresTeslaCannon", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Cold, Element.Poison, Element.Slash, Element.Machine }) },
            { "Artemis", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire, Element.Stab }, new Element[]{ Element.Cold, Element.Poison, Element.Dark, Element.Machine }) },
            { "Apollo", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire, Element.Stab }, new Element[]{ Element.Cold, Element.Poison, Element.Dark, Element.Machine }) },
            { "ThanatosHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Slash }, new Element[]{ Element.Cold, Element.Poison, Element.Holy, Element.Machine }) },
            { "ThanatosBody1", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Slash }, new Element[]{ Element.Cold, Element.Poison, Element.Holy, Element.Machine }) },
            { "ThanatosBody2", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Slash }, new Element[]{ Element.Cold, Element.Poison, Element.Holy, Element.Machine }) },
            { "ThanatosTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Slash }, new Element[]{ Element.Cold, Element.Poison, Element.Holy, Element.Machine }) },
            { "SupremeCalamitas", new Tuple<Element[], Element[]>(new Element[]{ Element.Cold, Element.Water, Element.Stab, Element.Holy, Element.Poison }, new Element[]{ Element.Fire, Element.Dark, Element.Unholy }) },
            { "SupremeCatastrophe", new Tuple<Element[], Element[]>(new Element[]{ Element.Cold, Element.Water, Element.Holy }, new Element[]{ Element.Fire, Element.Dark, Element.Unholy }) },
            { "PrimordialWyrmHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Stab, Element.Unholy }, new Element[]{ Element.Dark, Element.Slash, Element.Magic, Element.Water, Element.Cold }) },
            { "PrimordialWyrmBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Stab, Element.Unholy }, new Element[]{ Element.Dark, Element.Slash, Element.Magic, Element.Water, Element.Cold }) },
            { "PrimordialWyrmBodyAlt", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Stab, Element.Unholy }, new Element[]{ Element.Dark, Element.Slash, Element.Magic, Element.Water, Element.Cold }) },
            { "PrimordialWyrmTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Fire, Element.Stab, Element.Unholy }, new Element[]{ Element.Dark, Element.Slash, Element.Magic, Element.Water, Element.Cold }) },
            #endregion
        };
    }
}
