using System;
using System.Collections.Generic;

namespace CalRemix.UI.ElementalSystem
{
    public static class RemixElements
    {
        internal static Dictionary<string, Element[]> Item = new()
        {
            { "AcesLow", new Element[]{ Element.Stab }},
            { "AcidBow", new Element[]{ Element.Stab, Element.Poison }},
            { "AeroBolt", new Element[]{ Element.Magic }},
            { "AngelsThesis", new Element[]{ Element.Magic }},
            { "AOTE", new Element[]{ Element.Slash, Element.Magic }},
            { "Arngren", new Element[]{ Element.Stab }},
            { "AtlasMunitionsBeacon", new Element[]{ Element.Magic }},
            { "Axisdriver", new Element[]{ Element.Stab, Element.Machine, Element.Fire, Element.Cold }},
            { "Baow", new Element[]{ Element.Stab, Element.Magic }},
            { "BucketofCoal", new Element[]{ Element.Impact, Element.Dark }},
            { "BundleBones", new Element[]{ Element.Impact, Element.Dark }},
            { "ButterflyStaff", new Element[]{ Element.Magic }},
            { "CausticClaw", new Element[]{ Element.Poison }},
            { "ChainSaw", new Element[]{ Element.Slash, Element.Unholy }},
            { "ChainSpear", new Element[]{ Element.Stab, Element.Unholy }},
            { "ChristmasCarol", new Element[]{ Element.Magic, Element.Cold }},
            { "ColdheartIcicle", new Element[]{ Element.Stab, Element.Cold }},
            { "Confection", new Element[]{ Element.Impact, Element.Holy }},
            { "CorrosiveEyeStaff", new Element[]{ Element.Poison }},
            { "CursedSpear", new Element[]{ Element.Stab, Element.Dark }},
            { "DarkEnergyStaff", new Element[]{ Element.Dark }},
            { "Deicide", new Element[]{ Element.Impact, Element.Unholy }},
            { "DemonCore", new Element[]{ Element.Impact, Element.Dark }},
            { "Driftorcher", new Element[]{ Element.Slash, Element.Fire }},
            { "DualCane", new Element[]{ Element.Magic }},
            { "Dualpoon", new Element[]{ Element.Stab }},
            { "EcologicalCollapse", new Element[]{ Element.Impact, Element.Water }},
            { "Exodimus", new Element[]{ Element.Stab, Element.Holy }},
            { "Exosphear", new Element[]{ Element.Stab, Element.Machine, Element.Fire, Element.Cold }},
            { "FlamingIceBow", new Element[]{ Element.Stab, Element.Fire, Element.Cold }},
            { "FlounderMortar", new Element[]{ Element.Poison }},
            { "GearworkShield", new Element[]{ Element.Impact, Element.Machine }},
            { "GrandReef", new Element[]{ Element.Impact, Element.Water }},
            { "GrarbleBayonet", new Element[]{ Element.Stab }},
            { "GrarbleSpear", new Element[]{ Element.Stab }},
            { "HadopelagicEcho", new Element[]{ Element.Water }},
            { "HalbardoftheHolidays", new Element[]{ Element.Slash, Element.Cold }},
            { "Heterochromia", new Element[]{ Element.Stab, Element.Fire }},
            { "Homochromia", new Element[]{ Element.Stab, Element.Magic }},
            { "IchorDagger", new Element[]{ Element.Stab }},
            { "JetEngine", new Element[]{ Element.Impact, Element.Dark, Element.Machine }},
            { "MackerelStaff", new Element[]{ Element.Impact, Element.Holy }},
            { "Megaskeet", new Element[]{ Element.Stab, Element.Holy }},
            { "Morpho", new Element[]{ Element.Slash, Element.Fire }},
            { "Nystagmus", new Element[]{ Element.Impact, Element.Dark }},
            { "Ogscule", new Element[]{ Element.Unholy }},
            { "OnyxGunsaw", new Element[]{ Element.Slash, Element.Unholy }},
            { "OnyxGunblade", new Element[]{ Element.Impact, Element.Slash, Element.Dark }},
            { "PinesPenetrator", new Element[]{ Element.Stab, Element.Cold }},
            { "PlasmaflashBolt", new Element[]{ Element.Magic }},
            { "Prismachromancy", new Element[]{ Element.Magic }},
            { "ProfanedNucleus", new Element[]{ Element.Impact, Element.Holy, Element.Fire }},
            { "PungentBomber", new Element[]{ Element.Slash, Element.Poison }},
            { "RazorTeeth", new Element[]{ Element.Stab, Element.Poison }},
            { "RGBMurasama", new Element[]{ Element.Slash, Element.Machine }},
            { "SaltBooklet", new Element[]{ Element.Poison }},
            { "SaltWaterBolt", new Element[]{ Element.Poison, Element.Water }},
            { "SDOMG", new Element[]{ Element.Stab, Element.Machine }},
            { "ShadowsDescent", new Element[]{ Element.Impact, Element.Dark }},
            { "Snowgrave", new Element[]{ Element.Cold }},
            { "TendonTides", new Element[]{ Element.Slash, Element.Poison }},
            { "TenebrisTides", new Element[]{ Element.Slash, Element.Water }},
            { "Tetrachromancy", new Element[]{ Element.Magic, Element.Unholy }},
            { "TheDreamingGhost", new Element[]{ Element.Magic, Element.Holy }},
            { "ThunderBolt", new Element[]{ Element.Magic }},
            { "TitanTides", new Element[]{ Element.Slash, Element.Magic, Element.Dark }},
            { "TotalityTides", new Element[]{ Element.Slash, Element.Machine, Element.Fire, Element.Cold  }},
            { "Triploon", new Element[]{ Element.Stab }},
            { "Twentoon", new Element[]{ Element.Stab }},
            { "TwentyTwoon", new Element[]{ Element.Stab }},
            { "TyrantShield", new Element[]{ Element.Impact, Element.Holy }},
            { "UnsealedSingularity", new Element[]{ Element.Impact, Element.Magic, Element.Dark }},
            { "WinterBreeze", new Element[]{ Element.Stab, Element.Cold }},
            { "WrathoftheCosmos", new Element[]{ Element.Magic, Element.Dark }},
            { "WrathoftheDragons", new Element[]{ Element.Fire }},
            { "WrathoftheEldritch", new Element[]{ Element.Magic }},
            { "WrathoftheGods", new Element[]{ Element.Unholy }},
            { "WreathofBelial", new Element[]{ Element.Slash, Element.Cold, Element.Poison }},
            { "WulfrumLeechDagger", new Element[]{ Element.Stab, Element.Machine }},
        };
        // Vulnerable - Resistant
        internal static Dictionary<string, Tuple<Element[], Element[]>> Bosses = new()
        {
            { "Acideye", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Cold }, new Element[]{ Element.Poison, Element.Water, Element.Dark }) },
            //{ "DerellectBoss", new Tuple<Element[], Element[]>(new Element[]{ Element.Water, Element.Fire, Element.Impact }, new Element[]{ Element.Cold, Element.Poison, Element.Machine }) },

            { "Polyphemalus", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Impact }, new Element[]{ Element.Unholy }) },
            { "Astigmageddon", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Dark }, new Element[]{ Element.Unholy, Element.Magic, Element.Fire }) },
            { "Exotrexia", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Dark, Element.Fire }, new Element[]{ Element.Unholy, Element.Cold }) },
            { "Conjunctivirus", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Dark, Element.Water, Element.Holy }, new Element[]{ Element.Unholy, Element.Poison, Element.Fire }) },
            { "Cataractacomb", new Tuple<Element[], Element[]>(new Element[]{ Element.Stab, Element.Magic }, new Element[]{ Element.Unholy, Element.Dark, Element.Fire }) },

            { "WulfwyrmHead", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Machine, Element.Slash }) },
            { "WulfwyrmBody", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Machine, Element.Slash }) },
            { "WulfwyrmTail", new Tuple<Element[], Element[]>(new Element[]{ Element.Magic, Element.Water, Element.Fire }, new Element[]{ Element.Machine, Element.Slash }) },
        };
    }
}
